### ISSUE TITLE
TODO to get back to state I'm happy with

### ISSUE THREAD

**Issue by IainNZ** [IainNZ/PackageEvaluator.jl#77]
* [x] further parallelize - probably into release-even, release-odd, nightly-even, nightly-odd or A-M, N-Z, something like that
* [x] complete a full run
* [x] triage failures (on release will be sufficient for now)
* [x] improve provisioning using triage info
* [x] final manual run
* [ ] set it up to run as cron job

**Comment by IainNZ** [comment]
Seems to be working well, parallel run (2 release, 2 nightly) in progress right now. I'm going to throw it up on pkg.julialang.org and see whats failing (it won't be too bad) and go from there.

**Comment by IainNZ** [comment]
Just got to get back to cron jobs

**Comment by andrewcooke** [comment]
is this why my package doesn't appear in https://pkg.julialang.org/?pkg=ParserCombinator&ver=release ~36 hours after registering?  sorry if this is the wrong place to ask - I can't see anywhere on that side to give feedback or ask questions.

**Comment by IainNZ** [comment]
That I have to push it manually? Yeah. It'll be up in a few minutes though.

**Comment by andrewcooke** [comment]
ok, cool.  thanks.

**Comment by andrewcooke** [comment]
now it says "no description available".  is there documentation somewhere that says what is read?  i can find nothing at https://github.com/IainNZ/PackageEvaluator.jl/search?utf8=%E2%9C%93&q=description (i had assume it came from the github description when looking at other packages, but that is defined).

**Comment by IainNZ** [comment]
It'll appear tomorrow, it does come from the github description.
